### PR TITLE
Master

### PR DESCRIPTION
**Pull request by eecharlie**
Add getter & setter for compliance margin & slope. 
Example of more standard way of labeling & doing return types on these functions.

### CODE REVIEW

**Comment by eecharlie** [comment]
I don't know how or whether to update this actual pull request, so I'm closing and opening another.

**Comment by descampsa** [comment]
Ok, just so you know, the best way to make a pull request in github is to open a separate branch on your repository and make the pull request on that branch. 
That way, you can add commits to the branch and they are added to the push request.

**Comment by eecharlie** [comment]
Got it. So because I had done it from master, anything else I pushed would
be added to the request?

**Comment by descampsa** [comment]
Yes, apparently it is the case, i see five commits in this pull request (and in the other one), three merges from my repository, and your two actual commits.
Not a problem, i will squash them into one commit when merging, to be sure to keep the history clean.

Just avoid to push any new commit to your master branch before i have merged your pull request (i should be able to do it today or tomorrow)

**Pull request closed without merging**
